server.port : 9091
greet : Good Morning !!
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/configserverjpa
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
