server.port=9095
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/configserverjpa
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
